#version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red_familia
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["/app/wait-for-it.sh", "db:5432", "--", "gunicorn", "sitio_familia.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120"]
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles  # opcional, útil para revisar archivos estáticos
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=sitio_familia.settings
    depends_on:
      - db
    restart: always
    networks:
      - red_familia

volumes:
  postgres_data:

networks:
  red_familia:
